branding:
  icon: 'git-merge'
  color: 'orange'
inputs:
  from_branch:
    description: 'Name of the stable branch'
    required: false
    default: 'dev'
  to_branch:
    description: 'Name of the development branch'
    required: false
    default: 'main'
  allow_forks:
    description: 'Allow action to run on forks'
    required: false
    default: true
  user_name:
    description: 'User name for git commits'
    required: false
    default: 'GitHub Merge Action'
  user_email:
    description: 'User email for git commits'
    required: false
    default: 'actions@github.com'
  push_token:
    description: 'Environment variable containing the token to use for push'
    required: false
    default: 'GITHUB_TOKEN'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
