branding:
  icon: 'git-merge'
  color: 'orange'
inputs:
  from_branch:
    description: 'Name of the stable branch'
    required: false
    default: 'dev'
  to_branch:
    description: 'Name of the development branch'
    required: false
    default: 'main'
  allow_ff:
    description: 'Allow fast forward merge'
    required: false
    default: false
  allow_git_lfs:
    description: 'Allow git lfs support'
    required: false
    default: false
  ff_only:
    description: 'Refuse to perform a non fast forward merge (requires allow_ff=true)'
    required: false
    default: false
  allow_forks:
    description: 'Allow action to run on forks'
    required: false
    default: false
  user_name:
    description: 'User name for git commits'
    required: false
    default: 'GitHub Nightly Merge Action'
  user_email:
    description: 'User email for git commits'
    required: false
    default: 'actions@github.com'
  push_token:
    description: 'Environment variable containing the token to use for push'
    required: false
    default: 'GITHUB_TOKEN'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
